- repo: https://github.com/pre-commit/mirrors-flake8
  rev: 4.0.0
  hooks:
    - id: flake8

- repo: https://github.com/pre-commit/mirrors-isort
  rev: 5.12.0
  hooks:
    - id: isort

- repo: https://github.com/pre-commit/mirrors-black
  rev: stable
  hooks:
    - id: black